// Package pythongen generates a typed Python client for a webfunction
// package, targeting webfunction-python (the "webfunction" PyPI package).
//
// Confirmed design decisions, and how they differ from jsgen/phpgen/
// gogen/javagen/csharpgen/rubygen:
//
//  1. Real generated dataclasses, not docs-only annotations - explicitly
//     chosen over typing.TypedDict, directly informed by rubygen's own
//     v1->v2 lesson: real wrapper classes gave real dot-completion in any
//     editor with zero tooling, which is why Ruby's annotation-only v1
//     was abandoned. A genuine structural advantage over every other
//     target: a single .py file carries both real runtime behavior AND
//     native inline type hints together - no separate docs-only
//     annotation layer (unlike jsgen's JSDoc) and no companion signature
//     file needed (unlike rubygen's forced .rbs).
//  2. Both a sync Client and an async AsyncClient are generated by
//     default, in one file - mirroring webfunction-python's own dual API
//     rather than gating one behind a flag. Real added surface area (two
//     near-identical class bodies), same trade-off the library itself
//     made, not free.
//  3. Choices/values render as typing.Literal[...] type hints, not real
//     enum.Enum classes - lighter-weight than javagen's/csharpgen's real-
//     enum approach, no wire-value-mapping boilerplate needed, and
//     genuinely idiomatic for a Python API wrapper. One real, Python-
//     specific limitation found while implementing this: PEP 586 does not
//     allow float values as typing.Literal members, so a float-typed
//     choices field can't use Literal at all - see buildLiteralField in
//     dataclasses.go.
//  4. Numeric refinements collapse to plain int or float - Python has no
//     real sized-integer or single-precision-float types at all (ints are
//     arbitrary precision, floats are always the equivalent of a 64-bit
//     double). A real, flagged expressive-power gap, same category as
//     Go's/Java's real limitations, though in the opposite direction:
//     Python never loses precision doing this, it just can't express a
//     narrower type than what it collapses to.
//  5. A type union with more than one non-null alternative renders as a
//     genuine typing.Union[...] - unlike Go/Java/C#, Python can actually
//     express this natively, a real advantage rather than a gap.
//  6. Optional Arguments and nullable Attributes both make a field
//     typing.Optional[...] - ONE uniform mechanism for both, the same
//     collapsing gogen/csharpgen do for Go pointers/C#'s "?".
//  7. Pagination needs a single, REUSABLE generic wrapper per sync/async
//     (TypedPage(Generic[T]) / AsyncTypedPage(Generic[T])), not a fresh
//     class per paginated endpoint the way gogen/javagen/csharpgen need -
//     directly enabled by Python's real typing.Generic support, which
//     none of those three languages' codegen targets could lean on this
//     way (rubygen's v2 TypedPage is the closest precedent, but is only
//     genuinely generic in its companion .rbs, not the runtime .rb code
//     itself - Python's is generic in the actual class definition).
//  8. Escape hatch on the generated Client/AsyncClient wraps the real
//     webfunction.Client/AsyncClient via composition (not inheritance -
//     avoids any interaction with the real client's own __getattr__-based
//     dynamic dispatch). .call()/.package/.bearer_auth/.version/.pipeline
//     are all direct passthroughs - genuinely the simplest escape-hatch
//     story of any target so far, since the real library already exposes
//     bearer_auth/version/pipeline as plain public attributes rather than
//     getter/setter methods the way every other target's underlying
//     library does.
//  9. A zero-argument endpoint gets no args parameter at all, matching
//     gogen/javagen/csharpgen. An endpoint whose args are all individually
//     optional (or has none) gets a real Python default argument value
//     ("args: Optional[FooArgs] = None") - Python has genuine default
//     parameter values, so (like C#, and unlike Go's variadic-args trick
//     or Java's overload pair) this needs no workaround at all.
//  10. Args/Result conversion is asymmetric by design: encoding (a
//     dataclass -> the wire dict a call sends) uses a small SHARED generic
//     helper (_to_args_dict/_to_wire_value) that walks dataclasses.fields()
//     at runtime, since the encode direction only needs to know what a
//     value at hand actually IS, not what it's statically supposed to be.
//     Decoding (a wire dict -> a real dataclass instance) instead uses a
//     bespoke, fully-generated _from_dict classmethod per dataclass - a
//     raw wire dict doesn't inherently know it should become one
//     particular generated class, so that direction needs real per-field
//     generated code, same spirit as every other target's decodeResult/
//     DecodeResult<T> (though simpler here: only object.<n>-typed fields
//     ever need real conversion code at all, since json.loads already
//     produces the exactly-right native Python value for every scalar/
//     Any/Union/List-of-scalar field with zero conversion needed).
//  11. Pipelining is a smaller gap here than for every other target:
//     _to_wire_value passes an unrecognized value straight through
//     untouched, so a webfunction.Promise slipped into a typed field
//     actually works correctly at runtime (the underlying library's own
//     JSON encoder is already Promise-aware) - unlike Go/Java/C#/PHP,
//     where a pipelined typed call fails outright. Still only a static-
//     typing gap that's silently tolerated, not something advertised as
//     officially-supported typed pipelining; a real per-field static type
//     still just says (e.g.) str, and mypy would correctly flag passing a
//     Promise there.
//  12. --namespace is not used by this target at all (flagged in
//     cmd/codegen.go's usage text) - Python's own import system already
//     provides namespacing (import generated_module as x), so there's no
//     internal package/namespace concept needed inside the generated file
//     itself, unlike every other target.
package pythongen

import (
	"strings"

	"github.com/webfunction-protocol/webfunction-go"
)

// LibraryReference documents, in the generated header comment, what the
// generated file depends on.
const LibraryReference = "webfunction (pip install webfunction)"

// Generate builds a typed Python client for pkg, targeting
// webfunction-python. Unlike every other target, this one takes no
// namespace parameter - see the package doc comment, decision 12.
func Generate(pkg *webfunction.Package, sourceURL string) (string, error) {
	dc := newDataclassSet(pkg)
	endpoints := visibleEndpoints(pkg)

	// Pre-compute every endpoint's shapes first, so dataclass resolution
	// (which mutates dc as it goes, same as every other target's
	// structSet/recordSet) is complete before anything is rendered.
	infos := make(map[string]endpointInfo, len(endpoints))
	for _, ep := range endpoints {
		infos[ep.Name] = buildEndpointInfo(dc, ep)
	}

	var b strings.Builder
	writeHeader(&b, pkg, sourceURL)
	writeRuntimeHelpers(&b)
	dc.render(&b)

	writeClientClass(&b, pkg, sourceURL, endpoints, infos, false)
	b.WriteString("\n")
	writeClientClass(&b, pkg, sourceURL, endpoints, infos, true)

	return b.String(), nil
}

// endpointInfo holds everything about one endpoint needed to write its
// method on both Client and AsyncClient.
type endpointInfo struct {
	argsType     string // dataclass name for args, or "" if the endpoint takes none
	argsOptional bool

	paginated        bool
	itemType         string // Python type-hint for one page item; only set if paginated
	itemFromDictExpr string // a Python callable expression: "Cls._from_dict" or "lambda v: v"

	returnType       string // Python type-hint for a non-paginated return; ignored if paginated
	resultDecodeExpr string // expression (using "result") to decode the raw call result; "" for plain passthrough
}

func buildEndpointInfo(dc *dataclassSet, ep webfunction.Endpoint) endpointInfo {
	argFields := argumentFields(ep.Arguments)
	base := pythonClassName(ep.Name)
	argsDoc := ""
	if base != "" {
		argsDoc = base + "Args holds the arguments for the " + ep.Name + " endpoint."
	}
	argsType := dc.forFields(base+"Args", argsDoc, argFields, "argument")

	if ep.HasFlag("paginated") {
		itemType := "Any"
		itemFromDictExpr := "lambda v: v"
		resolve := func(refName string) string { return dc.resolveObject(refName, "attribute") }
		for _, a := range ep.Attributes {
			if a.Name != "page" {
				continue
			}
			for _, alt := range a.Type.Union {
				if alt.Base == "array" && alt.Of != nil {
					itemType = pythonType(*alt.Of, localTypes{}, false, resolve)
					decodeExpr := decodeValueExpr("v", *alt.Of, localTypes{}, resolve)
					if decodeExpr != "v" {
						itemFromDictExpr = "lambda v: " + decodeExpr
					}
				}
			}
		}
		return endpointInfo{
			argsType: argsType, argsOptional: allOptional(argFields),
			paginated: true, itemType: itemType, itemFromDictExpr: itemFromDictExpr,
		}
	}

	local := forEndpointReturn(dc, ep)
	resolve := func(refName string) string { return dc.resolveObject(refName, "attribute") }
	returnType := pythonType(ep.Returns, local, false, resolve)
	decodeExpr := decodeValueExpr("result", ep.Returns, local, resolve)
	if decodeExpr == "result" {
		decodeExpr = ""
	}

	return endpointInfo{
		argsType: argsType, argsOptional: allOptional(argFields),
		returnType: returnType, resultDecodeExpr: decodeExpr,
	}
}

// forEndpointReturn builds localTypes describing the endpoint's own
// inline return shape from its attributes - mirrors every other target's
// identical helper (same spec-reading rationale: attributes describes the
// object itself for a bare "object" return; a bare, untyped "array"
// return with attributes describes each item's shape, honored even
// though the spec's letter only defines attributes for the "object" case,
// because real-world packages use it that way).
func forEndpointReturn(dc *dataclassSet, ep webfunction.Endpoint) localTypes {
	if len(ep.Attributes) == 0 {
		return localTypes{}
	}
	fields := attributeFields(ep.Attributes)
	base := pythonClassName(ep.Name)
	doc := base + "Result is the result of the " + ep.Name + " endpoint."
	name := dc.forFields(base+"Result", doc, fields, "attribute")
	if name == "" {
		return localTypes{}
	}

	switch {
	case ep.Returns.HasBase("object"):
		return localTypes{object: name}
	case ep.Returns.HasBareArray():
		return localTypes{arrayOfItem: name}
	default:
		return localTypes{}
	}
}

func visibleEndpoints(pkg *webfunction.Package) []webfunction.Endpoint {
	out := make([]webfunction.Endpoint, 0, len(pkg.Endpoints))
	for _, ep := range pkg.Endpoints {
		if ep.HasFlag("private") {
			continue
		}
		out = append(out, ep)
	}
	return out
}

func writeHeader(b *strings.Builder, pkg *webfunction.Package, sourceURL string) {
	b.WriteString("# Code generated by wfn codegen --target python. DO NOT EDIT -\n")
	b.WriteString("# re-run codegen instead.\n")
	if pkg.Name != "" {
		b.WriteString("# Package: " + pkg.Name + "\n")
	}
	b.WriteString("# Source:  " + sourceURL + "\n")
	b.WriteString("#\n")
	b.WriteString("# IMPORTANT - depends on " + LibraryReference + ".\n\n")

	name := pkg.Name
	if name == "" {
		name = "(unnamed package)"
	}
	b.WriteString(`"""` + "Generated, typed client for the " + name + " webfunction package.\n\n")
	b.WriteString("Source: " + sourceURL + "\n" + `"""` + "\n\n")

	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("import dataclasses\n")
	b.WriteString("from dataclasses import dataclass, field\n")
	b.WriteString("from typing import Any, Dict, Generic, Iterator, List, Literal, Optional, TypeVar, Union, cast\n\n")
	b.WriteString("import webfunction\n\n\n")
	b.WriteString(`T = TypeVar("T")` + "\n\n\n")
}

// writeRuntimeHelpers writes the two small shared conversion functions
// plus the TypedPage/AsyncTypedPage generic wrapper classes - see the
// package doc comment, decisions 7 and 10.
func writeRuntimeHelpers(b *strings.Builder) {
	b.WriteString("def _to_wire_value(value: Any) -> Any:\n")
	writeDocstring(b, "    ", []string{
		"Recursively converts a generated dataclass instance (or a list of",
		"them) into its plain wire representation. Any other value - including",
		"an unresolved webfunction.Promise, when pipelining - passes through",
		"untouched: the underlying webfunction.Client's own JSON encoding is",
		"already Promise-aware, so this doesn't need to special-case it.",
	})
	b.WriteString("    if dataclasses.is_dataclass(value) and not isinstance(value, type):\n")
	b.WriteString("        return _to_args_dict(value)\n")
	b.WriteString("    if isinstance(value, list):\n")
	b.WriteString("        return [_to_wire_value(v) for v in value]\n")
	b.WriteString("    return value\n\n\n")

	b.WriteString("def _to_args_dict(obj: Any) -> Dict[str, Any]:\n")
	writeDocstring(b, "    ", []string{
		"Converts a generated Args dataclass instance into the wire dict",
		"shape, omitting any field left at its default None (an omitted",
		"optional argument, as opposed to an explicit null) and mapping field",
		"names back to their real, possibly-hyphenated wire names.",
	})
	b.WriteString("    result: Dict[str, Any] = {}\n")
	b.WriteString("    for f in dataclasses.fields(obj):\n")
	b.WriteString("        value = getattr(obj, f.name)\n")
	b.WriteString("        if value is None and f.default is None:\n")
	b.WriteString("            continue\n")
	b.WriteString("        result[f.metadata.get(\"wire_name\", f.name)] = _to_wire_value(value)\n")
	b.WriteString("    return result\n\n\n")

	writePageWrapper(b, "TypedPage", "webfunction.Page", false)
	writePageWrapper(b, "AsyncTypedPage", "webfunction.AsyncPage", true)
}

func writePageWrapper(b *strings.Builder, className, rawType string, async bool) {
	b.WriteString("class " + className + "(Generic[T]):\n")
	writeDocstring(b, "    ", []string{
		className + " is a page of results, wrapping the real " + rawType,
		"with item-level typing it can't provide by itself (its own .items",
		"is an untyped list).",
	})
	b.WriteString("\n")
	b.WriteString("    def __init__(self, raw: " + rawType + ", item_from_dict: Any) -> None:\n")
	b.WriteString("        self._raw = raw\n")
	b.WriteString("        self._item_from_dict = item_from_dict\n\n")

	b.WriteString("    @property\n")
	b.WriteString("    def items(self) -> List[T]:\n")
	b.WriteString("        return [self._item_from_dict(v) for v in self._raw.items]\n\n")

	b.WriteString("    @property\n")
	b.WriteString("    def has_next(self) -> bool:\n")
	b.WriteString("        return self._raw.has_next\n\n")

	b.WriteString("    @property\n")
	b.WriteString("    def has_previous(self) -> bool:\n")
	b.WriteString("        return self._raw.has_previous\n\n")

	asyncKw, awaitKw := "", ""
	if async {
		asyncKw, awaitKw = "async ", "await "
	}
	b.WriteString("    " + asyncKw + "def next_page(self) -> Optional[\"" + className + "[T]\"]:\n")
	b.WriteString("        result = " + awaitKw + "self._raw.next_page()\n")
	b.WriteString("        return None if result is None else " + className + "(result, self._item_from_dict)\n\n")

	b.WriteString("    " + asyncKw + "def previous_page(self) -> Optional[\"" + className + "[T]\"]:\n")
	b.WriteString("        result = " + awaitKw + "self._raw.previous_page()\n")
	b.WriteString("        return None if result is None else " + className + "(result, self._item_from_dict)\n\n")

	b.WriteString("    def __iter__(self) -> Iterator[T]:\n        return iter(self.items)\n\n")
	b.WriteString("    def __len__(self) -> int:\n        return len(self._raw.items)\n\n\n")
}

// writeClientClass writes either the sync Client or the async AsyncClient
// - the two are structurally identical apart from async/await keywords
// and which real underlying library class/page type they wrap, so both
// are produced from one function rather than duplicating the logic (see
// package doc comment, decision 2).
func writeClientClass(b *strings.Builder, pkg *webfunction.Package, sourceURL string, endpoints []webfunction.Endpoint, infos map[string]endpointInfo, async bool) {
	className := "Client"
	rawClientType := "webfunction.Client"
	pageWrapperClass := "TypedPage"
	closeMethod := "close"
	enter, exit := "__enter__", "__exit__"
	asyncKw, awaitKw := "", ""
	kindWord := ""
	if async {
		className = "AsyncClient"
		rawClientType = "webfunction.AsyncClient"
		pageWrapperClass = "AsyncTypedPage"
		closeMethod = "aclose"
		enter, exit = "__aenter__", "__aexit__"
		asyncKw, awaitKw = "async ", "await "
		kindWord = "async "
	}

	name := pkg.Name
	if name == "" {
		name = "(unnamed package)"
	}
	b.WriteString("class " + className + ":\n")
	writeDocstring(b, "    ", []string{
		"Generated, typed " + kindWord + "client for the " + name + " webfunction package.",
		"",
		"Source: " + sourceURL,
	})
	b.WriteString("\n")
	b.WriteString("    _SOURCE_URL = " + pyStr(sourceURL) + "\n\n")

	b.WriteString("    def __init__(self, raw: " + rawClientType + ") -> None:\n")
	b.WriteString("        self._raw = raw\n\n")

	b.WriteString("    @classmethod\n")
	b.WriteString("    " + asyncKw + "def new_client(cls, *, bearer_auth: Optional[str] = None, version: Optional[str] = None) -> \"" + className + "\":\n")
	writeDocstring(b, "        ", []string{"Builds a " + className + ", fetching the package definition from its source URL."})
	b.WriteString("        raw = " + awaitKw + rawClientType + ".from_package_endpoint(cls._SOURCE_URL, bearer_auth=bearer_auth, version=version)\n")
	b.WriteString("        return cls(raw)\n\n")

	b.WriteString("    " + asyncKw + "def call(self, name: str, args: Optional[Dict[str, Any]] = None) -> Any:\n")
	writeDocstring(b, "        ", []string{"Escape hatch for calling an endpoint this client doesn't have a typed method for."})
	b.WriteString("        return " + awaitKw + "self._raw.call(name, args or {})\n\n")

	b.WriteString("    @property\n    def package(self) -> Optional[\"webfunction.Package\"]:\n        return self._raw.package\n\n")

	b.WriteString("    @property\n    def bearer_auth(self) -> Optional[str]:\n        return self._raw.bearer_auth\n\n")
	b.WriteString("    @bearer_auth.setter\n    def bearer_auth(self, value: Optional[str]) -> None:\n        self._raw.bearer_auth = value\n\n")

	b.WriteString("    @property\n    def version(self) -> Optional[str]:\n        return self._raw.version\n\n")
	b.WriteString("    @version.setter\n    def version(self, value: Optional[str]) -> None:\n        self._raw.version = value\n\n")

	b.WriteString("    @property\n    def pipeline(self) -> Any:\n        return self._raw.pipeline\n\n")
	b.WriteString("    @pipeline.setter\n    def pipeline(self, value: Any) -> None:\n        self._raw.pipeline = value\n\n")

	b.WriteString("    " + asyncKw + "def " + closeMethod + "(self) -> None:\n        " + awaitKw + "self._raw." + closeMethod + "()\n\n")
	if async {
		b.WriteString("    async def " + enter + "(self) -> \"AsyncClient\":\n        return self\n\n")
		b.WriteString("    async def " + exit + "(self, *exc: Any) -> None:\n        await self.aclose()\n\n")
	} else {
		b.WriteString("    def " + enter + "(self) -> \"Client\":\n        return self\n\n")
		b.WriteString("    def " + exit + "(self, *exc: Any) -> None:\n        self.close()\n\n")
	}

	used := map[string]bool{}
	for _, ep := range endpoints {
		methodName := uniqueMethodName(used, pythonFieldName(ep.Name))
		writeMethod(b, ep, methodName, infos[ep.Name], async, pageWrapperClass)
	}
}

func writeMethod(b *strings.Builder, ep webfunction.Endpoint, methodName string, info endpointInfo, async bool, pageWrapperClass string) {
	asyncKw := ""
	if async {
		asyncKw = "async "
	}

	doc := docLines(ep.Docs)
	var extra []string
	for _, e := range ep.Errors {
		code := strings.TrimSpace(e.Code)
		if code == "" {
			continue
		}
		line := "webfunction.BadRequestError: code " + pyStr(code)
		errDocs := docLines(e.Docs)
		if len(errDocs) > 0 {
			line += " - " + errDocs[0]
		}
		extra = append(extra, line)
	}
	// Call-agnostic - webfunction-python can return either of these for
	// any endpoint regardless of what error codes (if any) that endpoint
	// itself declares, matching every other target's identical treatment.
	extra = append(extra, "webfunction.UnexpectedStatusCodeError: if the server responds with a non-200/400 status")
	extra = append(extra, "webfunction.JsonParseError: if the response body isn't valid JSON")
	if len(extra) > 0 {
		raises := []string{"Raises:"}
		for _, e := range extra {
			raises = append(raises, "    "+e)
		}
		extra = raises
	}

	returnType := info.returnType
	if info.paginated {
		returnType = "\"" + pageWrapperClass + "[" + info.itemType + "]\""
	}

	switch {
	case info.argsType == "":
		b.WriteString("    " + asyncKw + "def " + methodName + "(self) -> " + returnType + ":\n")
		// A bare {} literal has nothing for mypy --strict to infer a
		// concrete key/value type from, unlike the other two branches
		// (whose expressions already resolve to Dict[str, Any] via
		// _to_args_dict's own declared return type) - needs an explicit
		// annotation here specifically.
		writeMethodDocAndBody(b, doc, extra, ep, info, "raw_args: Dict[str, Any] = {}", async, pageWrapperClass)
	case info.argsOptional:
		b.WriteString("    " + asyncKw + "def " + methodName + "(self, args: Optional[" + info.argsType + "] = None) -> " + returnType + ":\n")
		writeMethodDocAndBody(b, doc, extra, ep, info, "raw_args = _to_args_dict(args) if args is not None else {}", async, pageWrapperClass)
	default:
		b.WriteString("    " + asyncKw + "def " + methodName + "(self, args: " + info.argsType + ") -> " + returnType + ":\n")
		writeMethodDocAndBody(b, doc, extra, ep, info, "raw_args = _to_args_dict(args)", async, pageWrapperClass)
	}
	b.WriteString("\n")
}

func writeMethodDocAndBody(b *strings.Builder, doc, extra []string, ep webfunction.Endpoint, info endpointInfo, rawArgsStmt string, async bool, pageWrapperClass string) {
	writeDocstring(b, "        ", doc, extra...)
	awaitKw := ""
	if async {
		awaitKw = "await "
	}
	b.WriteString("        " + rawArgsStmt + "\n")
	b.WriteString("        result = " + awaitKw + "self._raw.call(" + pyStr(ep.Name) + ", raw_args)\n")

	switch {
	case info.paginated:
		b.WriteString("        assert isinstance(result, " + pageWrapperRawType(pageWrapperClass) + ")\n")
		b.WriteString("        return " + pageWrapperClass + "(result, " + info.itemFromDictExpr + ")\n")
	case info.resultDecodeExpr != "":
		b.WriteString("        return " + info.resultDecodeExpr + "\n")
	default:
		// The underlying call() is genuinely, correctly typed Any (it's
		// the dynamic escape hatch) - cast() tells mypy to trust this
		// method's own declared return type instead of propagating that
		// Any outward, the standard idiom for this exact situation rather
		// than a blanket type: ignore comment. A no-op at runtime.
		returnType := info.returnType
		if returnType == "" {
			returnType = "Any"
		}
		b.WriteString("        return cast(" + returnType + ", result)\n")
	}
}

func pageWrapperRawType(pageWrapperClass string) string {
	if pageWrapperClass == "AsyncTypedPage" {
		return "webfunction.AsyncPage"
	}
	return "webfunction.Page"
}