package jsgen

import (
	"fmt"
	"sort"
	"strings"

	"wfn/webfunction"
)

// ImportSpecifier is the module specifier the generated file imports
const ImportSpecifier = "webfunction"

// Generate turns a fetched Package into the source of a JS module: it
// builds a Client against sourceURL, wraps it with a named method per
// endpoint (plus the underlying client's own package/call surface), and
// exports the wrapper as `client`.
func Generate(pkg *webfunction.Package, sourceURL string) (string, error) {
	var b strings.Builder

	writeHeader(&b, pkg, sourceURL)

	typedefs := newTypedefSet()
	// Pre-compute typedefs for every visible endpoint first, so the
	// typedef block above the methods is complete before any method
	// references one.
	endpointTypedef := make(map[string]string, len(pkg.Endpoints))
	for _, ep := range visibleEndpoints(pkg) {
		endpointTypedef[ep.Name] = typedefs.forEndpoint(ep)
	}
	b.WriteString(typedefs.render())

	b.WriteString(fmt.Sprintf("const rawClient = await Client.fromPackageEndpoint(%s);\n\n", jsStringLiteral(sourceURL)))

	methodNames := make(map[string]bool, len(pkg.Endpoints))
	for k := range jsReserved {
		methodNames[k] = true
	}

	b.WriteString("export const client = {\n")
	b.WriteString("  package: rawClient.package,\n")
	b.WriteString("  call: (name, args) => rawClient.call(name, args),\n")

	for _, ep := range visibleEndpoints(pkg) {
		methodName := uniqueMethodName(methodNames, camelCase(ep.Name))
		b.WriteString("\n")
		writeMethod(&b, ep, methodName, endpointTypedef[ep.Name])
	}

	b.WriteString("};\n")

	return b.String(), nil
}

// visibleEndpoints returns the package's endpoints in their original
// order, excluding any flagged "private" (per the spec, tooling SHOULD
// omit these from generated/published output).
func visibleEndpoints(pkg *webfunction.Package) []webfunction.Endpoint {
	out := make([]webfunction.Endpoint, 0, len(pkg.Endpoints))
	for _, ep := range pkg.Endpoints {
		if ep.HasFlag("private") {
			continue
		}
		out = append(out, ep)
	}
	return out
}

func uniqueMethodName(used map[string]bool, base string) string {
	name := base
	for i := 2; used[name]; i++ {
		name = fmt.Sprintf("%s%d", base, i)
	}
	used[name] = true
	return name
}

func writeHeader(b *strings.Builder, pkg *webfunction.Package, sourceURL string) {
	b.WriteString("// AUTO-GENERATED by wfn codegen --target js. Do not edit by hand -\n")
	b.WriteString("// re-run codegen instead.\n")
	if pkg.Name != "" {
		b.WriteString("// Package: " + pkg.Name + "\n")
	}
	b.WriteString("// Source:  " + sourceURL + "\n\n")
	b.WriteString(fmt.Sprintf("import { Client } from %s;\n\n", jsStringLiteral(ImportSpecifier)))
}

func writeMethod(b *strings.Builder, ep webfunction.Endpoint, methodName, objectTypedef string) {
	b.WriteString("  /**\n")

	for _, line := range docLines(ep.Docs) {
		if line == "" {
			b.WriteString("   *\n")
			continue
		}
		b.WriteString("   * " + line + "\n")
	}
	if ep.Docs != "" && len(ep.Arguments) > 0 {
		b.WriteString("   *\n")
	}

	if len(ep.Arguments) > 0 {
		b.WriteString("   * @param {Object} args\n")
		for _, arg := range ep.Arguments {
			writeArgDoc(b, arg)
		}
	}

	b.WriteString("   * @returns {Promise<" + returnType(ep, objectTypedef) + ">}\n")
	b.WriteString("   */\n")
	b.WriteString(fmt.Sprintf("  %s(args) {\n", methodName))
	b.WriteString(fmt.Sprintf("    return rawClient.call(%s, args);\n", jsStringLiteral(ep.Name)))
	b.WriteString("  },\n")
}

func writeArgDoc(b *strings.Builder, arg webfunction.Argument) {
	typ := jsdocType(arg.Type, "", false)

	name := "args." + arg.Name
	if !arg.Required() {
		name = "[" + name + "]"
	}

	line := "   * @param {" + typ + "} " + name

	desc := strings.TrimSpace(strings.ReplaceAll(arg.Docs, "\n", " "))
	note := hintNote(arg.Hints)
	switch {
	case desc != "" && note != "":
		line += " - " + desc + " " + note
	case desc != "":
		line += " - " + desc
	case note != "":
		line += " - " + note
	}

	if len(arg.Choices) > 0 {
		line += " " + choicesNote(arg.Choices)
	}

	b.WriteString(line + "\n")
}

func choicesNote(choices []interface{}) string {
	strs := make([]string, len(choices))
	for i, c := range choices {
		strs[i] = fmt.Sprintf("%v", c)
	}
	sort.Strings(strs)
	return "(one of: " + strings.Join(strs, ", ") + ")"
}

func returnType(ep webfunction.Endpoint, objectTypedef string) string {
	return jsdocType(webfunction.JSONType(ep.Returns), objectTypedef, false)
}

// jsStringLiteral renders a Go string as a single-quoted JS string literal.
func jsStringLiteral(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return "'" + s + "'"
}